### ISSUE TITLE
error: Could not compile `image`.

### ISSUE THREAD

**Issue by tylerhjones** [PistonDevelopers/opengl_graphics#275]
```
error[E0001]: unreachable pattern
   --> /Users/tyler/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/./src/dynimage.rs:632:9
    |
632 |         _ => Err(image::ImageError::UnsupportedError(format!("A decoder for {:?} is not available.", format))),
    |         ^ this is an unreachable pattern

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `image`.
```

This is on osx, a vanilla clone. 
rustc 1.15.1 (021bd294c 2017-02-08)
cargo 0.16.0-nightly (3568be9 2016-11-26)

**Comment by abaybektursun** [comment]
For some reason image does not compile with rustc 1.15.1. I had the same version of rust and cargo on Windows, CentOS, Ubuntu machines, and image would not compile. Updating Rust resolved the issue.

You can quickly update your Rust by running:
`
rustup self uninstall && curl https://sh.rustup.rs -sSf | sh
`
